CREATE VIEW V_ESTADO AS
SELECT  C.ID_CLIENTE, 
        C.NOME, 
        C.SEXO,
        R.ESTADO
FROM CLIENTE C 
INNER JOIN REGIAO R  
ON C.ID_REGIAO = R.ID_REGIAO
WHERE C.SEXO = 'F' AND R.ESTADO LIKE 'M%';