/* Modelagem Básica */

/*CRIAR BANCO DE DADOS */
CREATE DATABASE exer01


/*CADASTRDO DE CLIENTE (NOME, CPF, EMAIL, TELEFONE, ENDEREÇO, SEXO)*/

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY,
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30),
    CPF CHAR(11) UNIQUE,
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100)
);


CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR (100),
    SEXO VARCHAR (10),
    EMAIL VARCHAR (100),
    DEPARTAMENTO INT (100),
    ADMISSAO DATE,
    SALARIO INTEGER,
    CARGO VARCHAR(100),
    ID_REGIAO INT,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO)
);


CREATE TABLE CARGO (
    ID_CARGO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100)

);

CREATE TABLE LIVRO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LIVRO VARCHAR (100),
    AUTOR VARCHAR (100),
    SEXO CHAR (1),
    PAGINAS INT,
    EDITORA VARCHAR (30),
    VALOR DECIMAL(10,2),
    UF CHAR (2),
    ANO DATE
);


CREATE TABLE REGIAO (
    ID_REGIAO INT IDENTITY(1,1) PRIMARY KEY,
    ESTADO_EXT VARCHAR (100),
    ESTADO CHAR(2)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100),
    SALA VARCHAR(100)
);


CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR (100),
    SEXO CHAR (1),
    ENDERECO VARCHAR (100),
    CEP CHAR(8),
    TELEFONE1 VARCHAR(30),
    TELEFONE2 VARCHAR(30),
    EMAIL VARCHAR (100),
    ID_REGIAO INT,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO)
)

CREATE TABLE AUTOR(
    ID_AUTOR INT IDENTITY (1,1) PRIMARY KEY,
    AUTOR VARCHAR(100),
    SEXO CHAR(1),
    FORMACAO VARCHAR(100),
    NASCIMENTO DATE,   
)


CREATE TABLE EDITORA (
    ID_EDITORA INT IDENTITY (1,1) PRIMARY KEY,
    EDITORA VARCHAR(100),
    ENDERECO VARCHAR(100),
    NUMERO VARCHAR (30),
    BAIRRO VARCHAR(100),
    CEP CHAR(8),
    TEL1 VARCHAR(30),
    TEL2 VARCHAR(30),
    EMAIL VARCHAR (100),
    ID_REGIAO INT,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO) 
)


ELECT * FROM VENDEDOR;


/*Alias Colunas*/
SELECT ENDERECO AS LOGRADOURO, CPF, EMAIL FROM CLIENTE;

/*CARACTER CORINGA % -> QUALQUER COISA*/
SELECT BAIRRO FROM CLIENTE
WHERE BAIRRO LIKE '%a'

/*Alias Colunas*/
SELECT ENDERECO AS LOGRADOURO, CPF, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE WHERE SEXO='F'
/* 1 - Trazer todos os dados*/
SELECT * FROM LIVRO
/* 2 - Trazer o nome do livro e o nome da editora*/
SELECT LIVRO, EDITORA FROM LIVRO
/* 3 - Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino */
SELECT LIVRO, UF, SEXO FROM LIVRO WHERE SEXO='M'
/* 4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo femino*/
SELECT LIVRO, PAGINAS, AUTOR, SEXO FROM LIVRO WHERE SEXO='F'
/* 5 - Trazer os valores dos livros das editiras de São Paulo*/
SELECT LIVRO, VALOR FROM LIVRO
/* 6 - Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo
ou Rio de Janeiro (Questão Desafio)*/
SELECT AUTOR, SEXO FROM LIVRO --OR -> Para que a saida da query seja verdadeira, basta que apenas uma condicção seja verdadeira
WHERE SEXO='M' AND (UF='SP' OR UF='RJ'); --AND -> Para que a saída seja verdadeira todas as condições precisam ser verdadeiras.


/* OR - OU */
SELECT * FROM CLIENTE

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

/* AND - E */
SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE 'RJ';



-- OR traz todo mundo com pelo menos uma das duas condições
-- AND Traz apenas o rREGIAO


/*Junção de tabelas CLIENTE E REGIAO*/
SELECT C.ID_CLIENTE, C.NOME, C.SEXO, R.ESTADO
FROM CLIENTE C 
INNER JOIN REGIAO R  
ON C.ID_REGIAO = R.ID_REGIAO
WHERE C.SEXO = 'F' AND R.ESTADO LIKE 'M%';


/*Comandos COMMIT E ROLLBACK*/
SELECT * FROM CLIENTE
WHERE NOME = 'LIVIA'
AND sexo = 'F'



/*WHERE = SELEÇÃO*/


/*Criando POROCEDURE para inserir dados na tabela departamento*/
SELECT * FROM DEPARTAMENTO;

SELECT * FROM CLIENTE
WHERE ID_CLIENTE IN (3,5,6,7);

/*-------------------------------------------------------------------------*/



